import Head from 'next/head';
import Link from 'next/link';
import Layout from '../components/layout';
import Header from '../components/header';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Luke Prosser</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <Header />
        <main>
          <h1>
            Welcome to <Link href='/posts/first-post'>lukesprosser.com</Link>
          </h1>
        </main>

        <footer></footer>
      </Layout>
    </div>
  );
}
