import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';
import { getSortedPostsData } from '../lib/posts';
import Layout from '../components/layout';
import SignupForm from '../components/signupForm';

export async function getStaticProps() {
  const allPostsData = getSortedPostsData();
  return {
    props: {
      allPostsData,
    },
  };
}

export default function Home({ allPostsData }) {
  return (
    <div>
      <Head>
        <title>Luke Prosser</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <main>
          <section className='gap-3 my-12 md:flex md:items-center'>
            <div>
              <h1 className='py-4 text-5xl font-medium sm:text-6xl'>
                Hi, I&apos;m Luke.
              </h1>
              <p className='mb-6 text-2xl sm:text-4xl'>
                I&apos;m a Web Developer based in Wales, UK.
              </p>
              <p className='text-lg font-light sm:text-xl'>
                I enjoy building websites and applications using full-stack
                JavaScript technologies like React and Node.js, and sharing what
                I learn along the way.
              </p>
            </div>
            <SignupForm />
            <div
              className='ml-form-embed'
              data-account='1301826:u6l0i3y6u9'
              data-form='1755242:v5e9n4'
            ></div>
          </section>
          <section className='mt-20'>
            <h2 className='text-3xl sm:text-4xl'>Latest from the blog</h2>
            <ul>
              {allPostsData.map(
                ({ id, title, cover_image, image_alt, tags, excerpt }) => (
                  <li
                    key={id}
                    className='pb-8 my-12 border-b-2 sm:grid sm:grid-cols-3 sm:gap-6'
                  >
                    <div>
                      <Image
                        src={`/images/posts/${id}/${cover_image}`}
                        alt={image_alt}
                        width={1280}
                        height={853}
                      />
                    </div>
                    <div className='mt-3 sm:mt-0 sm:col-span-2'>
                      <h3 className='text-xl md:text-2xl'>
                        <Link href={`/posts/${id}`}>
                          <a>{title}</a>
                        </Link>
                      </h3>
                      <div className='mt-2 text-xs tracking-widest md:text-sm lg:text-base'>
                        {tags.map((tag) => (
                          <span
                            key={tag}
                            className='mr-5 text-indigo-700 dark:font-medium hover:text-indigo-500 dark:text-indigo-400 dark:hover:text-indigo-300'
                          >
                            {tag.toUpperCase()}
                          </span>
                        ))}
                      </div>
                      <p className='mt-6 font-light md:text-lg'>{excerpt}</p>
                    </div>
                  </li>
                )
              )}
            </ul>
          </section>
        </main>
      </Layout>
    </div>
  );
}
